notifications:
  email: false
language: node_js
node_js:
- '7'
script:
- npm run build
cache:
  yarn: true
  directories:
  - apps/api-server/node_modules
  - apps/webapp/node_modules
  - packages/fire-starter/node_modules
  - packages/fire-ui/node_modules
  - node_modules

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/deploy-to-now.sh
    on:
      all_branches: true
